version: '3'
services:
  elasticsearch:
    # PER UTILIZZARE IL REGISTRY LOCALE AGGIUNGERE QUESTA RIGA ALLE PREFERENZE DEL DOCKER DAEMON
    #"insecure-registries" : [
    # "tower01-it-d.local:5000",
    # "tower01-it-d.local:5001"
    #]
    # E SCOMMENTARE LA RIGA SEGUENTE 
    #image: tower01-it-d.local:5001/elasticsearch/elasticsearch:6.8.2    
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    ports:
    - "9200:9200"
    user:
      elasticsearch
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=*
      - -Ehttp.cors.allow-headers=Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
  kibana:
    # PER UTILIZZARE IL REGISTRY LOCALE AGGIUNGERE QUESTA RIGA ALLE PREFERENZE DEL DOCKER DAEMON
    #"insecure-registries" : [
    # "tower01-it-d.local:5000",
    # "tower01-it-d.local:5001"
    #]
    # E SCOMMENTARE LA RIGA SEGUENTE 
    #image: tower01-it-d.local:5001/kibana/kibana:6.8.2
    image: docker.elastic.co/kibana/kibana:6.8.2
    ports:
    - "5601:5601"
    links:
    - elasticsearch
  app:
    image: node:12.9.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn start"